fix: Fix CVE for Jakarta(RDCC-3237)
hmcts/rd-judicial-api pull request #160
Opened 2021-08-13 15:48 UTC by pksaxena01

### JIRA link (if applicable) ###
RDCC-3237

### Change description ###
This change will address the Jakarta CVE

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ X] No
```

2021-08-13 15:48 UTC, shreedhar-hmcts submitted a review, later dismissed

2021-08-13 15:48 UTC, bkpatel81 approved these changes

2021-08-13 15:48 UTC, kavithagade12 submitted a review, later dismissed

2021-08-13 16:27 UTC, viswajit-kuna approved these changes

2021-08-13 16:28 UTC, souravroy2021 requested changes

2021-08-13 16:28 UTC, souravroy2021 commented on build.gradle
> +    implementation (group: 'org.springframework.boot', name: 'spring-boot-starter-web'){
We may have added spring boot starter web dependency twice, should we get rid of one of these dependencies ?

2021-08-16 15:38 UTC, SujeethKumarAri approved these changes

2021-08-16 15:39 UTC, rajkatla-hmcts approved these changes

2021-08-16 15:46 UTC, souravroy2021 approved these changes

2021-08-16 15:46 UTC, merged