Feat:RDCC-3697:Added constraint to roles table
hmcts/rd-judicial-api pull request #193
Opened 2021-11-26 14:12 UTC by shivajihmcts

### JIRA link  ###
https://tools.hmcts.net/jira/browse/RDCC-3697

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2021-11-26 14:24 UTC, AdilOoze approved these changes

2021-11-26 14:28 UTC, ManishParyani approved these changes

2021-11-26 14:51 UTC, ManishParyani requested changes
I think this will fail due to existing duplicate records. Before applying constraint you need to delete existing duplicate records.

2021-11-26 15:36 UTC, SujeethKumarAri approved these changes

2021-11-29 12:41 UTC, shivajihmcts commented
Flyway changes are not required

2021-11-29 12:41 UTC, closed without merging