Rdcc 3979 code
hmcts/rd-judicial-api pull request #240
Opened 2022-02-18 10:35 UTC by shivajilokare

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-02-21 18:56 UTC, SujeethKumarAri requested changes

2022-02-21 18:56 UTC, SujeethKumarAri commented on src/main/resources/db/migration/V1_30__update_service_ticket_code_for_sscs.sql
> +DELETE FROM judicial_service_code_mapping WHERE service_id ='21' OR service_id ='55';
you can move these scripts to the above created file, so that we can avoid having an extra file

2022-02-23 09:50 UTC, kavithagade12 commented on src/main/resources/db/migration/V1_29__insert_sscs_record.sql
> +DELETE FROM judicial_service_code_mapping WHERE service_id ='21' OR service_id ='55';
Please use the following query for delete:

DELETE FROM judicial_service_code_mapping WHERE service_id in ('21', '55');
DELETE FROM judicial_ticket_code_mapping WHERE ticket_code  in ('363', '376');

2022-02-23 10:29 UTC, shivajilokare commented
new consolidated PR is raised , closing this one

2022-02-23 10:29 UTC, closed without merging