added personal code changes
hmcts/rd-judicial-api pull request #267
Opened 2022-03-08 14:23 UTC by ManishParyani

### JIRA link (if applicable) ###
[RDCC-4152](https://github.com/hmcts/rd-judicial-api/tree/RDCC-4152)

### Change description ###
Added personal code

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-03-14 09:06 UTC, SujeethKumarAri requested changes
Can you please resolve these code smells? https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&sinceLeakPeriod=true&pullRequest=267&id=RDJUDICIALAPI

2022-03-14 09:21 UTC, kavithagade12 approved these changes

2022-03-14 15:50 UTC, SujeethKumarAri reviewed
You need to increase  the mutation coverage may be to 85 as part of this ticket - https://github.com/hmcts/rd-judicial-api/blob/RDCC-4152/build.gradle#L242

2022-03-15 11:20 UTC, amitkumarshrivastava approved these changes

2022-03-15 11:55 UTC, SujeethKumarAri approved these changes

2022-03-17 12:25 UTC, merged