[RDCC-6538]eLinks : Write End to end Integration test for Success/Failure
hmcts/rd-judicial-api pull request #555
Opened 2023-04-25 15:30 UTC by manukundloo-hmcts

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDCC-6538

### Change description ###
[RDCC-6538]eLinks : Write End to end Integration test for Success/Failure

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-04-26 10:02 UTC, manukundloo-hmcts commented
Closing the PR since it is failing due to time out .

2023-04-26 11:28 UTC, prudhvi-maddineni approved these changes

2023-05-02 12:29 UTC, vasthav-patta requested changes
validate idam_id instead of object id

2023-05-02 13:41 UTC, manukundloo-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksEndToEndIntegrationTest.java
> +        assertEquals("94772643-2c5f-4f84-8731-3dd7c25c9e11",
Thank you @vasthav-patta ,Added assertion for IDAM Id and loaded response from json file.

2023-05-02 14:19 UTC, vasthav-patta approved these changes

2023-05-03 09:36 UTC, merged