DTSRD-2029: eLinks : Post-Production rollout for Strategic solution: CHG5014213
hmcts/rd-judicial-api pull request #800
Opened 2024-05-07 12:59 UTC by kiran-yenigala-hmcts

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/DTSRD-2029

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-05-07 13:01 UTC, SabinaHMCTS approved these changes

2024-05-07 13:12 UTC, lukasz-wolski submitted a review, later dismissed

2024-05-13 16:04 UTC, lukasz-wolski submitted a review, later dismissed

2024-05-13 16:42 UTC, SabinaHMCTS approved these changes

2024-05-15 22:07 UTC, rajkatla-hmcts requested changes

2024-05-23 13:55 UTC, kiran-yenigala-hmcts commented on src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/RegionMappingRepository.java
>  public interface RegionMappingRepository extends JpaRepository<RegionMapping, String> {
removed

2024-05-23 13:58 UTC, kiran-yenigala-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/CheckForSearchV2UsersIntegrationTest.java
> +import uk.gov.hmcts.reform.judicialapi.elinks.controller.request.UserSearchRequest;
removed

2024-05-23 14:58 UTC, rajkatla-hmcts requested changes

2024-05-23 14:58 UTC, rajkatla-hmcts commented on src/main/java/uk/gov/hmcts/reform/judicialapi/elinks/repository/RegionMappingRepository.java
>  public interface RegionMappingRepository extends JpaRepository<RegionMapping, String> {
i see this repository class still exists, this can be removed as it is not used anywhere

2024-05-23 16:11 UTC, rajkatla-hmcts approved these changes

2024-06-05 14:41 UTC, lukasz-wolski submitted a review, later dismissed

2024-08-05 08:56 UTC, closed without merging