DTSRF-2900: INC5616053 - Judge isn't showing on Judicial Lookup
hmcts/rd-judicial-api pull request #854
Opened 2024-06-13 16:27 UTC by kiran-yenigala-hmcts

### Jira link (if applicable)

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-06-13 16:43 UTC, SabinaHMCTS approved these changes

2024-06-14 08:02 UTC, aneesaHMCTS submitted a review, later dismissed

2024-06-28 15:46 UTC, kiran-yenigala-hmcts commented
Close this PR, as these changes are implemented into https://github.com/hmcts/rd-judicial-api/pull/800

2024-07-04 16:07 UTC, rajkatla-hmcts requested changes

2024-07-04 16:07 UTC, rajkatla-hmcts commented on src/integrationTest/java/uk/gov/hmcts/reform/judicialapi/elinks/ElinksJobSchedulerIntegrationTest.java
> +    @DisplayName("Should run scheduler job and load elinks api's data when appointment id null for authorisations")
move this test to people integration test

2024-07-05 15:54 UTC, rajkatla-hmcts approved these changes

2024-07-05 15:54 UTC, merged